export const ADD_NUMBER = "ADD_NUMBER";
export const RESET_NUMBER = "RESET_NUMBER";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
